version: "2"

run:
    timeout: 5m

linters:
    default: standard
    enable:
        - bodyclose
        - errorlint
        - usestdlibvars
        - wsl_v5
        - funlen
        - nestif
        - cyclop
        - gocognit
        - gocritic
        - noctx
        - misspell
        - prealloc
        - nilnil
        - forcetypeassert
        - musttag
        - unparam
        - unconvert
        - revive
        - wrapcheck
        - modernize
        - perfsprint
        - nlreturn

        - nolintlint
        - err113

    settings:
        wrapcheck:
            ignore-package-globs:
                - codeberg.org/upPollo/parsec/internal/*
        nolintlint:
            require-explanation: true

formatters:
    enable:
        - gofumpt
        - gci

    settings:
        gci:
            sections:
                - standard
                - default
                - prefix(codeberg.org/upPollo/parsec)
