version: "2"

run:
    timeout: 5m

linters:
    default: standard
    enable:
        - bodyclose
        - errorlint
        - usestdlibvars
        - wsl_v5
        - funlen
        - nestif
        - cyclop
        - gocognit
        - gocritic
        - noctx
        - misspell
        - prealloc
        - nilnil
        - forcetypeassert
        - musttag
        - unparam
        - unconvert
        - revive

    settings:
        revive:
            rules:
                - name: exported
                  severity: warning

formatters:
    enable:
        - gofumpt
        - gci

    settings:
        gci:
            sections:
                - standard
                - default
                - prefix(codeberg.org/upPollo/parsec)
