version: "2"

run:
    timeout: 5m

linters:
    default: standard
    enable:
        - bodyclose
        - errorlint
        - usestdlibvars
        - wsl_v5

formatters:
    enable:
        - gofumpt
