package nfo

import "strings"

// StreamingServiceNames maps streaming service tags to their full descriptive names.
var StreamingServiceNames = map[string]string{
	"3SAT":  "3Sat",
	"9NOW":  "9Now",
	"AND":   "Animation Digital Network",
	"AE":    "A&E",
	"AJAZ":  "Al Jazeera English",
	"ALL4":  "All4 (Channel 4)",
	"AMBC":  "ABC (US)",
	"AMC":   "AMC",
	"AMZN":  "Amazon",
	"ANLB":  "AnimeLab",
	"ANPL":  "Animal Planet",
	"AOL":   "AOL",
	"ARD":   "ARD Mediathek",
	"ARDP":  "ARD Plus",
	"ARTE":  "ARTE",
	"AS":    "Adult Swim",
	"ATK":   "America's Test Kitchen",
	"ATV":   "Apple TV (channel content)",
	"ATVP":  "Apple TV+ (original content)",
	"AUBC":  "ABC (AU) iView",
	"BCORE": "Sony Pictures Core",
	"BKPL":  "Blackpills",
	"BNGE":  "Binge",
	"BOOM":  "Boomerang",
	"BRAV":  "BravoTV",
	"CANP":  "Canal+",
	"CBC":   "CBC",
	"CBS":   "CBS",
	"CC":    "Comedy Central",
	"CCGC":  "Comedians in Cars Getting Coffee",
	"CHGD":  "CHRGD",
	"CLBI":  "Club illico",
	"CMAX":  "Cinemax",
	"CMOR":  "C More",
	"CMT":   "Country Music Television",
	"CN":    "Cartoon Network",
	"CNBC":  "CNBC",
	"CNLP":  "Canal+",
	"COOK":  "Cooking Channel",
	"CR":    "Crunchy Roll",
	"CRIT":  "Criterion Channel",
	"CRKL":  "Crackle",
	"CSPN":  "CSpan",
	"CTV":   "CTV",
	"CUR":   "CuriosityStream",
	"CW":    "The CW",
	"CWS":   "CWSeed",
	"DCU":   "DC Universe",
	"DDY":   "Digiturk Dilediğin Yerde",
	"DEST":  "Destination America",
	"DHF":   "Deadhouse Films",
	"DISC":  "Discovery Channel",
	"DIY":   "DIY Network",
	"DOCC":  "Doc Club",
	"DRPO":  "Dropout",
	"DSCP":  "Discovery+",
	"DSKI":  "Daisuki",
	"DSNP":  "Disney+",
	"DSNY":  "Disney",
	"DTV":   "DirecTV Now",
	"EPIX":  "EPIX",
	"ESPN":  "ESPN",
	"ESQ":   "Esquire",
	"ETTV":  "El Trece",
	"ETV":   "E!",
	"FAM":   "Family",
	"FJR":   "Family Jr",
	"FOOD":  "Food Network",
	"FOX":   "Fox",
	"FPT":   "FPT Play",
	"FREE":  "Freeform",
	"FTV":   "France.tv",
	"FUNI":  "Funimation",
	"FXTL":  "Foxtel Now",
	"FYI":   "FYI Network",
	"GC":    "NHL GameCenter",
	"GLBL":  "Global",
	"GLBO":  "Globoplay",
	"GO90":  "go90",
	"HBO":   "HBO",
	"HGTV":  "HGTV",
	"HIDI":  "HIDIVE",
	"HIST":  "History Channel",
	"HLMK":  "Hallmark",
	"HMAX":  "HBO Max",
	"HULU":  "Hulu",
	"ID":    "Investigation Discovery",
	"IFC":   "IFC",
	"IP":    "BBC iPlayer",
	"IT":    "iTunes",
	"ITV":   "ITV",
	"JOYN":  "Joyn",
	"KAYO":  "Kayo Sports",
	"KIKA":  "KiKA",
	"KNOW":  "Knowledge Network",
	"KNPY":  "Kanopy",
	"LIFE":  "Lifetime",
	"LN":    "Loving Nature",
	"MA":    "Movies Anywhere",
	"MAX":   "Max (Warner Bros. Discovery)",
	"MNBC":  "MSNBC",
	"MTOD":  "Motor Trend OnDemand",
	"MTV":   "MTV",
	"NATG":  "National Geographic",
	"NBA":   "NBA League Pass",
	"NBC":   "NBC",
	"NF":    "Netflix",
	"NFL":   "NFL Network",
	"NFLN":  "NFL Now",
	"NICK":  "Nickelodeon",
	"NOW":   "Now (Sky)",
	"NRK":   "Norsk Rikskringkasting",
	"PA":    "Project Alpha",
	"PBS":   "PBS",
	"PBSK":  "PBS Kids",
	"PCOK":  "Peacock",
	"PLAY":  "Google Play",
	"PLUZ":  "Pluzz",
	"PMNT":  "Paramount Network",
	"PMTP":  "Paramount+",
	"POGO":  "PokerGo",
	"PSN":   "Playstation Network",
	"PUHU":  "puhutv",
	"RKTN":  "Rakuten TV",
	"ROKU":  "The Roku Channel",
	"RSTR":  "Rooster Teeth",
	"RTE":   "RTÉ",
	"RTL":   "RTL+",
	"RTLP":  "RTL+",
	"SBS":   "SBS (AU)",
	"SESO":  "Seeso",
	"SHDR":  "Shudder",
	"SHMI":  "Shomi",
	"SHO":   "Showtime",
	"SKST":  "SkyShowtime",
	"SNET":  "Sportsnet",
	"SPIK":  "Spike",
	"SPRT":  "Sprout",
	"STAN":  "Stan",
	"STRP":  "Star+",
	"STZ":   "Starz",
	"SVT":   "Sveriges Television",
	"SWER":  "SwearNet",
	"SYFY":  "SyFy",
	"TBS":   "TBS",
	"TEN":   "TenPlay",
	"TFOU":  "TFOU",
	"TIMV":  "TIMvision",
	"TLC":   "TLC",
	"TOU":   "Ici TOU.TV",
	"TRVL":  "Travel Channel",
	"TUBI":  "TubiTV",
	"TV3":   "TV3 (IE)",
	"TV4":   "TV4 (SE)",
	"TVL":   "TVLand",
	"UFC":   "UFC",
	"UKTV":  "UKTV",
	"UNIV":  "Univision",
	"USAN":  "USA Network",
	"VH1":   "VH1",
	"VIAP":  "Viaplay",
	"VICE":  "Viceland",
	"VLCT":  "Velocity",
	"VMEO":  "Vimeo",
	"VRV":   "VRV",
	"VTRN":  "VET Tv",
	"WME":   "WatchMe",
	"WNET":  "W Network",
	"WOWTV": "WowTV (Sky)",
	"WPU":   "Waipu",
	"WWEN":  "WWE Network",
	"XBOX":  "Xbox Video",
	"YHOO":  "Yahoo",
	"YT":    "YouTube",
	"ZDF":   "ZDF Mediathek",
}

func expandServiceName(tag string) string {
	if name, ok := StreamingServiceNames[strings.ToUpper(tag)]; ok {
		return name
	}

	return tag
}
