when:
    - event: [push, pull_request]

variables:
    - &golang "golang:1.25-alpine"
    - &golang_cgo "golang:1.25"
    - &golangci_lint "golangci/golangci-lint:v2.12-alpine"

steps:
    vendor:
        image: *golang
        commands: go mod vendor

    lint:
        image: *golangci_lint
        commands: golangci-lint run

    test:
        image: *golang_cgo
        commands: go test -race -cover ./...
