when:
    - event: [push, tag, cron]

variables:
    - &golang "golang:1.25-alpine"

steps:
    vendor:
        image: *golang
        commands: go mod vendor

    lint:
        image: *golang
        commands: |
            go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
            golangci-lint run

    test:
        image: *golang
        commands: go test ./...
