when:
    - event: push
      branch: main

steps:
    ready-release:
        image: woodpeckerci/plugin-ready-release-go
        settings:
            forge_token:
                from_secret: forge_token
            git_email: parsec-bot@noreply.codeberg.org
            git_name: Parsec Bot
